const Products = [
    {
      id: 1,
      category: "Hombre",
      title: "American Script Sweatshirt",
      description: "La American Script Sweatshirt está confeccionada con una mezcla de algodón y poliéster peinado para mayor suavidad y calidez sin perder transpirabilidad. Esta prenda tiene una silueta amplia y holgada. Incluye sutiles detalles bordados.",
      price: 85.00,
      image: "https://i1.adis.ws/i/carhartt_wip/I025475_1CR_XX-ST-01/american-script-sweatshirt-teide-7879.png",
      stock: 100,
    },
    {
        id: 2,
        category: "Hombre",
        title: "S/S Script Embroidery T-Shirt",
        description: "La S/S Script Embroidery T-Shirt se ha confeccionado en punto de algodón ligero y presenta un corte holgado. La camiseta está adornada con un logotipo con texto bordado en el pecho.",
        price: 29.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I030435_1GM_XX-ST-01/s-s-script-embroidery-t-shirt-buffalo-white-3875.png",
        stock: 100,
    },
    {
        id: 3,
        category: "Hombre",
        title: "L/S Pocket T-Shirt",
        description: "La L/S Pocket T-Shirt está confeccionada en punto de algodón y cuenta con un bolsillo en el pecho con una clásica etiqueta tejida de Carhartt WIP que pone el toque final.",
        price: 39.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I030437_89_XX-ST-01/l-s-pocket-t-shirt-black-277.png",
        stock: 100,
    },
    {
        id: 4,
        category: "Hombre",
        title: "Half Zip American Script Sweatshirt",
        description: "La Half Zip American Script Sweatshirt está confeccionada con una mezcla de algodón y poliéster de 12,3 onzas peinado para mayor suavidad y calidez sin perder transpirabilidad.",
        price: 95.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I027014_1D4_XX-ST-01/half-zip-american-script-sweatshirt-icarus-7272.png",
        stock: 100,
    },
    {
        id: 5,
        category: "Mujer",
        title: "W' Modular Jacket",
        description: "La Women's Modular Jacket está confeccionada en nailon ligero y está forrada con tafetán. Tiene cuello y cierre delantero con cremallera, así como dos bolsillos delanteros.",
        price: 130.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031604_1CY_XX-ST-01/w-modular-jacket-atom-blue-929.png",
        stock: 100,
    },
    {
        id: 6,
        category: "Mujer",
        title: "W' Master Pant",
        description: "El Women's Master Pant es un clásico pantalón chino confeccionado en nuestra fuerte sarga “Dunmore”, una resistente mezcla de algodón y poliéster de peso medio.",
        price: 79.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I025061_1CL_02-ST-01/w-master-pant-phoenix-rinsed-7963.png",
        stock: 100,
    },
    {
        id: 7,
        category: "Mujer",
        title: "W' Alma Bib Overall",
        description: "El Women's Alma Bib Overall es un modelo utilitario que combina dos tejidos básicos de Carhartt WIP. La prenda tiene una base de denim Perry de peso medio y está rematada con paneles de tejido ripstop Columbia en las rodillas, y bolsillos.",
        price: 89.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031932_01_06-ST-01/w-alma-bib-overall-blue-stone-washed-215.png",
        stock: 100,
    },
    {
        id: 8,
        category: "Mujer",
        title: "W' L/S Coleen T-Shirt",
        description: "La Women's L/S Coleen T-Shirt es una camiseta de manga larga y corte regular confeccionada en punto de algodón orgánico ligero.",
        price: 39.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031626_1J5_XX-ST-01/w-l-s-coleen-t-shirt-coleen-stripe-citron-white-871.png",
        stock: 100,
    },
    {
        id: 9,
        category: "Accesorios",
        title: "Madison Pack Socks",
        description: "Confeccionados en hilo de algodón y elástico, los Madison Pack Socks tienen un panel de felpa francesa con textura en el interior para darle un tacto más suave.",
        price: 19.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I030923_1A5_XX-ST-01",
        stock: 100,
    },
    {
        id: 10,
        category: "Accesorios",
        title: "Philis Backpack",
        description: "La Philis Backpack es un modelo ampliable fabricado con lona de poliéster reciclado y repelente al agua.",
        price: 79.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031575_1CN_XX-ST-01",
        stock: 100,
    },
    {
        id: 11,
        category: "Accesorios",
        title: "Jake Hip Bag",
        description: "Fabricada en lona de mezcla de poliéster reciclado, la Jake Hip Bag sin forro es un modelo repelente al agua.",
        price: 39.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031476_89_XX-ST-01",
        stock: 100,
    },
    {
        id: 12,
        category: "Accesorios",
        title: "New Frontier Cap",
        description: "La gorra desestructurada de seis paneles New Frontier Cap presenta una visera firme y curva.",
        price: 29.00,
        image:"https://i1.adis.ws/i/carhartt_wip/I031684_K02_XX-ST-01",
        stock: 100,
    },
]

export const getProducts = () => {
    return new Promise((resolve, reject) => {
      resolve(Products),
      reject(new Error("Error"))
    });
  }